server:
  port: 9090
spring:
  application:
    name: spring-sensors-location-service
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: optional:configtree:/etc/config/